import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#016065',
  },
  gambar: {
    width: 95,
    height: 95,
    marginTop: 50,
  },
  nama: {
    fontSize: 20,
    fontWeight: 'bold',
    display: 'flex',
    lineHeight: 27,
    alignItems: 'center',
    color: '#fff',
    marginTop: 30,
  },
  username: {
    fontSize: 13,
    lineHeight: 18,
    display: 'flex',
    alignItems: 'center',
    color: '#b0b0b0',
    marginRight: 200,
    marginTop: 10,
  },
  foll: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 25,
  },
  foll1: {
    fontSize: 18,
    fontWeight: 'bold',
    lineHeight: 25,
    display: 'flex',
    alignItems: 'center',
    color: '#fff',
    marginLeft: 10,
  },
  foll2: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: 'bold',
    display: 'flex',
    marginLeft: 10,
    marginRight: 25,
    alignItems: 'center',
    color: '#b0b0b0',
  },
  pop: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 50,
  },
  star: {
    width: 28,
    height: 28,
    color: '#fff',
    marginRight: 20,
  },
  tstar: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 22,
    display: 'flex',
    alignItems: 'center',
    color: '#fff',
    marginRight: 150,
  },
  bm: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
  },
  bm1: {
    tintColor: '#ffff',
    marginRight: 20,
  },

  bm2: {
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 22,
    display: 'flex',
    alignItems: 'center',
    color: '#fff',
    marginRight: 130,
  },
});
